name: Clippy
on: [push]

jobs:
  clippy:
    name: Clippy (1.63.0)
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          components: clippy
          override: true
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy (1.63.0)
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings
